# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rush01' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rush01
  pod 'MapboxNavigation', '~> 0.15.0'
  pod 'MapboxGeocoder.swift', '~> 0.10'
end